trigger:
  branches:
    include:
    - '*'

pr: none

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UseDotNet@2
  displayName: Setup dotnet 3.1.x
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    arguments: '--test-adapter-path:. --logger:"junit;LogFilePath=artifacts\test-output.xml"'
    publishTestResults: false

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    mergeTestResults: true
